### ISSUE TITLE
Rule: consistent use of single/double quotes

### ISSUE THREAD

**Issue by patwork** [rrdelaney/jadelint#12]
A simple one: should choose one type of quotes (single/double option?) and stick to it (document wide):

``` jade
//- Invalid
a(href="/kill", title='me')

//- Invalid
a(href="/johhny.html")
    img(src='mnemonic.png')

//- Valid (with option "single"?)
a(href='/', title='root')
    img(src='beer.jpg')

//- Valid (with option "double"?)
a(href="/just", title="do")
    img(src="it.svg")
```

**Comment by rrdelaney** [comment]
I'll implement this with the option to specify quote style

**Comment by rrdelaney** [comment]
Began working on this in https://github.com/rrdelaney/jadelint/commit/08827e65d7e70a9dec55920320ce2e6a764ed597

**Comment by patwork** [comment]
cool, hope there will be no problems with var str = 'this "is" funny' like tricks

**Comment by rrdelaney** [comment]
This is done. Instead of globally enforcing the rule, it now works like

``` jade
//- Invalid
a(a="a" b='b')

//- Valid
a(a="a" b="b")
c(c='c' d='d')
```

You can enforce only one to be used in the `.jadelintrc` with the setting

``` json
{
  "UseConsistentQuotes": {
    "force": "<quote style>"
  }
}
```

For example, if the line was `"force": "'"`, `a(href="a")` would be illegal anywhere.

If you have anymore questions, I created a bitter for jadelint.
