### ISSUE TITLE
Update docs if you want: now works with my Atom package

### ISSUE THREAD

**Issue by ghost** [rrdelaney/jadelint#7]
I just incorporated jadelint into my linting package (that was previously using the jade compiler) https://atom.io/packages/linter-jade

**Comment by rrdelaney** [comment]
If you have any specific feature requests I'd be glad to implement them!

**Comment by rrdelaney** [comment]
The linter now catches compile errors. I mean, it always did but I just had some silly semantics in there that cause the linter to throw errors.

The error reported is in the normal format of `{name, level, filename, line}`, so I hope this helps!

**Comment by ghost** [comment]
Nice, if it's in the same format as the other errors they should be consumed automatically.  And I think I can get ride of the jade compiler with that change :)

The other nice things to have in general would be:
- [ ] column numbers
- [ ] return the rule that caused an error (preferably in err.code)
- [ ] why are 'ignore' rules being processed?  It seems like they'd just slow down the linter.  I'm filtering them out at the moment

Thanks for your efforts!

[edit] And random thing I just noticed -- I went to RPI :smiley:

**Comment by rrdelaney** [comment]
RPI thing is cool :+1: 
- So column number in general would be pretty difficult, and would require some serious reworking of the core linter.
- I can return the code on compile errors really easily.

And I process ignore rules because
- The linter is fast, most rules are just simple checks so I'm not worried about slowing it down really
- You get the whole view of the lint results, regardless of the configuration

I'll do the error code thing now!

**Comment by rrdelaney** [comment]
So normal errors are formatted 

``` json
{
    "name": "...",
    "level": "...",
    "filename": "...",
    "line": 0
}
```

but now compile errors have a special `code` attribute that returns the jade compiler code (eg `JADE:ELSE_NO_IF`)
